name: CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  # Docker image configuration
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE_NAME: supunishara/react-app
  DOCKER_IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (for better builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Login to Docker Registry
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t cicd/reactjs-app .

      - name: Publish Image to Docker Hub
        run: docker push cicd/reactjs-app:latest

  deploy:
    needs: build-and-push
    runs-on: aws-ec2
    steps:
      - name: Pull image from docker hub
        run: docker pull cicd/reactjs-app:latest
      - name: Delete Old Container
        run: docker rm -f reactContainer
      - name: Run the docker Container
        run: docker run -d -p 3000:80 --name reactContainer cicd/reactjs-app
